# Generated by Django 3.2.3 on 2021-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pasta', models.CharField(max_length=100)),
                ('sauce', models.CharField(max_length=100)),
                ('vegetables', models.CharField(max_length=100)),
            ],
        ),
    ]
