# Generated by Django 3.2.3 on 2021-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='cookTime',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='directions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ingredients',
            field=models.CharField(max_length=100),
        ),
    ]
