# Generated by Django 3.2.3 on 2021-07-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_meat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meats',
            field=models.ManyToManyField(to='main_app.Meat'),
        ),
    ]
